### ISSUE TITLE
Error when abridged flag is on

### ISSUE THREAD

**Issue by sabyasachee** [usc-sail/mica-text-script-parser#5] opened 2020-06-13 18:21 UTC
[salvation_road.pdf](https://github.com/usc-sail/mica-text-script-parser/files/4775170/salvation_road.pdf)

I get the following error when I run the parse_script_noindent on the above pdf with the abridged flag on -

```
Traceback (most recent call last):
  File "/proj/sbaruah/movie/mica-text-script-parser/parse_scripts_noindent.py", line 351, in <module>
    parse(file_orig, save_dir, abr_flag, tag_flag)
  File "/proj/sbaruah/movie/mica-text-script-parser/parse_scripts_noindent.py", line 342, in parse
    dial_str = ' '.join(abridged_script[i + 1].split('D:')[1].split())
IndexError: list index out of range
```

Can you please look into it? It seems the program expects **D** tag to always follow a **C** tag, which does not happen at some point for the linked pdf.

**Comment by ncsandeepacharya** [comment] 2020-06-26 04:03
I just pushed a change that fixes this by:
(1) improving detection of character name, dialogue, dialogue metadata (earlier version was dropping dialogues, which the parser was expecting, hence one cause of the error)
(2) only printing when character speaks (earlier version assumed that characters always speak, hence another cause of the error)

Could you test this latest version again and let me know if the error still turns up? Once you confirm that all is good, I'll close this issue.

**Comment by sabyasachee** [comment] 2020-07-05 23:07
The previous error seems to have been solved. However, I still get the following two kinds of errors:

1. When I run on file `/data/sbaruah/movie/files/temp/63.txt`, I get the following exception:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-57-a295378d9191> in <module>
----> 1 parse('/data/sbaruah/movie/files/temp/63.txt', '/data/sbaruah/movie/files/temp/', 'on', 'on', 'on')

/proj/sbaruah/movie/mica_text_script_parser/parse_scripts_noindent.py in parse(file_orig, save_dir, abr_flag, tag_flag, char_flag, save_name, abridged_name, tag_name)
    308         tag_vec = get_meta(script_noind, tag_vec, tag_set, meta_thresh, meta_set, sent_thresh, bound_ind, trans_ind)
    309         # DETECT CHARACTER-DIALOGUE
--> 310         tag_vec = get_char_dial(script_noind, tag_vec, tag_set, char_max_words)
    311         # DETECT SCENE DESCRIPTION
    312         tag_vec = get_scene_desc(script_noind, tag_vec, tag_set)

/proj/sbaruah/movie/mica_text_script_parser/parse_scripts_noindent.py in get_char_dial(script_noind, tag_vec, tag_set, char_max_words)
    122                 while dial_flag > 0:
    123                         line_ind = x + dial_flag
--> 124                         if len(script_noind[line_ind].split()) > 0:
    125                                 dial_str, dial_meta_str, rem_str = separate_dial_meta(script_noind[line_ind])
    126                                 if dial_str != '' or rem_str != '':

IndexError: list index out of range
```

2. When I run on file `/data/sbaruah/movie/files/temp/153.txt`, I get the following exception:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-2251af41ab28> in <module>
----> 1 parse('/data/sbaruah/movie/files/temp/153.txt', '/data/sbaruah/movie/files/temp/', 'on', 'on', 'on')

/proj/sbaruah/movie/mica_text_script_parser/parse_scripts_noindent.py in parse(file_orig, save_dir, abr_flag, tag_flag, char_flag, save_name, abridged_name, tag_name)
    334         while find_same(tag_valid) > 0 or find_arrange(tag_valid) > 0:
    335                 tag_valid, script_valid = merge_tag_lines(tag_valid, script_valid)
--> 336                 tag_valid, script_valid = rearrange_tag_lines(tag_valid, script_valid)
    337                 max_rev += 1
    338                 if max_rev == 1000: raise AssertionError("Too many revisions. Something must be wrong.")

/proj/sbaruah/movie/mica_text_script_parser/parse_scripts_noindent.py in rearrange_tag_lines(tag_merged, script_merged)
    249         if len(dial_met_ind) > 0:
    250                 for tag_ind in dial_met_ind:
--> 251                         temp_ind = min([i for i, x in enumerate(tag_merged[(tag_ind + 1): ]) if x != 'D'])
    252                         # REARRANGE TAGS
    253                         tag_merged[tag_ind: (tag_ind + temp_ind)] = tag_merged[(tag_ind + 1): (tag_ind + temp_ind + 1)]

ValueError: min() arg is an empty sequence
```

Can you please have a look?

Also, I see that the program removes the source file if it is a pdf. It would be better I think if we could make that feature optional. Sometimes, users might not want to remove the pdf script.

**Comment by ncsandeepacharya** [comment] 2020-07-29 02:50
Can you check now? I just pushed a version that resolves these issues. As far as I can tell, these issues were caused by:
(1) Inefficient detection of tags that needed to be merged; I have put in a more robust implementation
(2) No characters being detected in the file 153.txt; I have modified the logic for C detection accordingly

As for the file removal, that's odd. The script should only remove the _auxiliary txt_ file that's generated when processing the **input pdf** file; it shouldn't remove the **pdf** file itself. In any case, I have separated the processing of input files based on whether they are pdf or txt, just to be safe. Could you check again and let me know if the issue persists?

**Closed as completed** 2020-08-23 19:00 UTC
